repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace
  #      - id: check-ast
  #      - id: check-executables-have-shebangs
  #      - id: debug-statements
  #      - id: name-tests-test
  #        args: [ "--django" ]

  # BANDIT
  #  - repo: https://github.com/pycqa/bandit
  #    rev: 1.7.0
  #    hooks:
  #      - id: bandit
  #        args: [ "-iii", "-ll" ]

  - repo: https://github.com/psf/black
    rev: 19.3b0
    hooks:
      - id: black
        language_version: python3

#  - repo: https://gitlab.com/PyCQA/flake8
#    rev: 3.8.3
#    hooks:
#      - id: flake8
#        args: [ --max-line-length=99 ]
#        additional_dependencies: [
#            "flake8-bugbear",
#            "flake8-comprehensions",
#            "flake8-mutable",
#            "flake8-print",
#            "flake8-simplify",
#        ]
