# Generated by Django 3.2.4 on 2021-07-30 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("invite", "0003_auto_20210730_0118")]

    operations = [
        migrations.AlterField(
            model_name="invite",
            name="guest",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="event_invitations",
                to="invite.guest",
            ),
        )
    ]
